# Generated by Django 5.1.3 on 2024-12-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category_post_notification_comment_bookmark"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
    ]
