# Generated by Django 5.1.3 on 2024-12-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
