# Generated by Django 5.1.3 on 2025-01-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Category"},
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
